import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Explicit top-level sidebar (order = this array), replacing the old
// one-big-autogen setup. Grouping here is sidebar-only — file paths and
// URLs are untouched (doc/blog URLs are frozen).
//
// Each category still autogenerates its contents from its directory, so
// new pages added inside a directory appear automatically; only a brand-new
// top-level directory needs to be registered here.
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'index',
    'getting-started',
    {
      type: 'category',
      label: 'Introduction',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'introduction'}],
    },
    {
      type: 'category',
      label: 'Adoption Guides',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'adoption'}],
    },
    {
      type: 'category',
      label: 'Cloud Security',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'cloud-security'}],
    },
    {
      type: 'category',
      label: 'App & Infrastructure Scanning',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'security-scanning'}],
    },
    {
      type: 'category',
      label: 'Vulnerabilities & Risk',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'vulnerability-risk'}],
    },
    'reports-and-ai',
    {
      type: 'category',
      label: 'Compliance & GRC',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'compliance'}],
    },
    {
      type: 'category',
      label: 'Threat Intelligence & AI',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'ai-threat-intelligence'}],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'integrations'}],
    },
    {
      type: 'category',
      label: 'API & Automation',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'api-automation'}],
    },
    {
      type: 'category',
      label: 'API Reference',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'api-reference'}],
    },
    {
      type: 'category',
      label: 'Platform Security & Hardening',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'authentication'}],
    },
    {
      type: 'category',
      label: 'On-Premises',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'on-premises'}],
    },
    {
      type: 'category',
      label: 'Industries',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'industries'}],
    },
    {
      // Reference & about-the-platform docs that used to sit loose at the
      // sidebar's top level. Grouped here (sidebar-only; same URLs). Most
      // are also reachable from the navbar "Reference" dropdown.
      type: 'category',
      label: 'Resources',
      collapsed: true,
      items: [
        'cli-and-cicd',
        'architecture',
        'trust-and-security',
        'troubleshooting',
        'faq',
        'glossary',
      ],
    },
  ],
};

export default sidebars;
